# -*- coding: utf-8 -*-
"""gcloudtesting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qnx-Sv-UyfkwXfLJfiZOe1qBX9UQsyjo
"""

print("Hello World")

print("GCloud Lab")
